### ISSUE TITLE
Bug : Navigation Bar Overflowing in Mobile View

### ISSUE THREAD

**Issue by TartejBrothers** [GriffinBaxter/GriffinBaxter.com#1]
The navigation bar is overflowing in the mobile view, it is the same as the desktop view, maybe it is not made responsive yet. 
![image](https://github.com/GriffinBaxter/GriffinBaxter.com/assets/112921727/b02e61d8-32db-4fb6-b8ef-854bdeb2614f)

## Suggestion
- Try using menu with grip line for mobile menu (example attached).
![image](https://github.com/GriffinBaxter/GriffinBaxter.com/assets/112921727/37cb5c79-dfe8-4b20-b7bb-4c7bf69f0641)

**Comment by GriffinBaxter** [comment]
Thanks for this pointing out, and good suggestion for the mobile menu design! My site definitely needs work in terms of mobile responsiveness, I'll leave this issue open to remind me to get around to it. 😁

**Comment by GriffinBaxter** [comment]
This has been fixed in the latest commit (https://github.com/GriffinBaxter/GriffinBaxter.com/commit/3713b1f2fa1ba90ee3eb26ff216cd73d6ec5ce1b), thanks for opening the issue!
