### ISSUE TITLE
[Button not Working] : Menu Button Not Closing the Menu

### ISSUE THREAD

**Issue by TartejBrothers** [GriffinBaxter/GriffinBaxter.com#2]
# Issue: 
- The navbar menu button, opens the popup for the menu, but when clicked again, it should close the menu, but instead it does nothing.

# UI Issue: 
- The menu might look better if it is 100% width or a little bigger with some space on top.
- It not center aligned either.

# Fix :
- The best fix might be making it come below the navbar rather that going in the navbar.

**Comment by GriffinBaxter** [comment]
This has been fixed in the latest commit (https://github.com/GriffinBaxter/GriffinBaxter.com/commit/5933efef2b40eb8416503bc4206483c654509bf8), thanks for opening the issue!
