### ISSUE TITLE
[UI Issue] : Overflow in the mobile view

### ISSUE THREAD

**Issue by TartejBrothers** [GriffinBaxter/GriffinBaxter.com#4]
# Issue
- The navbar was working great, but now it has some overflow space
![image](https://github.com/GriffinBaxter/GriffinBaxter.com/assets/112921727/27be6de2-9c73-4262-9219-9b65f954f55c)
- This might be due to something down taking more than 100vw

# Fix
- Try using 
```css
body{
       overflow-x: hidden
}
```

**Comment by GriffinBaxter** [comment]
This has been fixed in the latest commit (https://github.com/GriffinBaxter/GriffinBaxter.com/commit/de20d048bffd801e0763f16e5e4fb12f5c304061), thanks for opening the issue!
